"""Render the daily decode report as HTML (email-friendly) and Markdown."""
from __future__ import annotations

from datetime import datetime
from typing import Optional


_BIAS_COLOR = {
    "STRONG BULLISH": "#0f8a3c", "BULLISH": "#2fae5e",
    "NEUTRAL": "#7a7a7a",
    "BEARISH": "#e0663a", "STRONG BEARISH": "#c62828",
}
_DIR_EMOJI = {
    "UP": "🟢⬆️", "SIDEWAYS-UP": "🟢↗️", "RANGE": "🟡➡️",
    "SIDEWAYS-DOWN": "🔴↘️", "DOWN": "🔴⬇️",
}


def _levels_rows(levels: list) -> str:
    rows = []
    for l in levels:
        rows.append(
            f"<tr><td>{l['strike']:.0f}</td><td>{l['kind']}</td>"
            f"<td>{l['basis']}</td><td>{l['oi']:,.0f}</td>"
            f"<td>{l['oi_change']:+,.0f}</td><td>{l['distance_pct']:+.2f}%</td>"
            f"<td style='font-size:12px'>{l['reaction']}</td></tr>"
        )
    return "\n".join(rows)


def _scenarios_html(scenarios: list) -> str:
    if not scenarios:
        return "<li>No level-based scenarios available.</li>"
    return "\n".join(
        f"<li><b>{s['trigger']}</b> → {s['then']}</li>" for s in scenarios
    )


def render_html(decode_result: dict, predictions: dict, levels: dict,
                report_date: str, symbol: str = "NIFTY") -> str:
    bias = decode_result["bias"]
    color = _BIAS_COLOR.get(bias, "#333")
    nd = predictions["next_day"]
    nw = predictions["next_week"]

    signal_rows = "\n".join(
        f"<tr><td>{s['name']}</td><td>{s['score']:+.2f}</td>"
        f"<td>{s['weight']:.2f}</td><td style='font-size:12px'>{s['note']}</td></tr>"
        for s in decode_result["signals"]
    )

    m = decode_result.get("metrics", {})
    metric_items = "".join(
        f"<span style='display:inline-block;margin:2px 10px 2px 0'>"
        f"<b>{k}</b>: {v:,.0f}</span>" if isinstance(v, (int, float))
        else f"<span style='display:inline-block;margin:2px 10px 2px 0'><b>{k}</b>: {v}</span>"
        for k, v in m.items()
    )

    return f"""\
<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FII/DII Decode — {report_date}</title></head>
<body style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;
 max-width:820px;margin:0 auto;padding:16px;color:#1c1c1c;background:#fff">
<h1 style="margin-bottom:0">📊 FII/DII/Pro/Client Decode</h1>
<div style="color:#666">{symbol} · {report_date} · generated {datetime.now():%Y-%m-%d %H:%M IST}</div>

<div style="margin:18px 0;padding:14px 16px;border-radius:10px;background:{color}12;
 border-left:6px solid {color}">
  <div style="font-size:22px;font-weight:700;color:{color}">Bias: {bias}</div>
  <div>Composite score <b>{decode_result['composite']:+.2f}</b> ·
   Confidence <b>{decode_result['confidence']:.0f}%</b></div>
</div>

<h2>🔮 Next-Day Prediction</h2>
<div style="font-size:18px">{_DIR_EMOJI.get(nd['direction'],'')} <b>{nd['direction']}</b>
 · confidence {nd['confidence']:.0f}%</div>
<p style="color:#444">{nd['rationale']}</p>
<b>What to do at levels tomorrow:</b>
<ul>{_scenarios_html(nd['scenarios'])}</ul>

<h2>🗓️ Next-Week Outlook (Mon–Fri)</h2>
<div style="font-size:18px">{_DIR_EMOJI.get(nw['direction'],'')} <b>{nw['direction']}</b>
 · confidence {nw['confidence']:.0f}%</div>
<p style="color:#444">{nw['rationale']}</p>

<h2>🧭 Institutional Levels & Expected Reaction</h2>
<table border="0" cellpadding="6" cellspacing="0" width="100%"
 style="border-collapse:collapse;font-size:14px">
<tr style="background:#f2f2f2;text-align:left">
 <th>Strike</th><th>Type</th><th>Basis</th><th>OI</th><th>ΔOI</th><th>Dist</th><th>Expected reaction</th></tr>
{_levels_rows(levels.get('levels', []))}
</table>
<p><b>Max Pain:</b> {levels.get('max_pain','n/a')} ·
 <b>PCR:</b> {levels.get('pcr','n/a')} — {levels.get('pcr_signal','')}</p>

<h2>🧬 Decode Signals</h2>
<table border="0" cellpadding="6" cellspacing="0" width="100%"
 style="border-collapse:collapse;font-size:14px">
<tr style="background:#f2f2f2;text-align:left">
 <th>Signal</th><th>Score</th><th>Weight</th><th>Note</th></tr>
{signal_rows}
</table>

<h2>📈 Key Metrics</h2>
<div style="font-size:13px;color:#333">{metric_items}</div>

<hr style="margin-top:26px;border:none;border-top:1px solid #eee">
<p style="font-size:11px;color:#999">
Auto-generated by FII-DII-Decode. Educational analysis of publicly available NSE
participant data — <b>not investment advice</b>. Markets are risky; do your own research.</p>
</body></html>"""


def render_markdown(decode_result: dict, predictions: dict, levels: dict,
                    report_date: str, symbol: str = "NIFTY") -> str:
    nd = predictions["next_day"]
    nw = predictions["next_week"]
    lines = [
        f"# FII/DII/Pro/Client Decode — {symbol} — {report_date}",
        "",
        f"**Bias:** {decode_result['bias']}  ·  composite `{decode_result['composite']:+.2f}`  ·  confidence {decode_result['confidence']:.0f}%",
        "",
        "## Next-Day Prediction",
        f"- Direction: **{nd['direction']}** (confidence {nd['confidence']:.0f}%)",
        f"- {nd['rationale']}",
        "- Scenarios:",
    ]
    for s in nd["scenarios"]:
        lines.append(f"  - **{s['trigger']}** → {s['then']}")
    lines += ["", "## Next-Week Outlook (Mon–Fri)",
              f"- Direction: **{nw['direction']}** (confidence {nw['confidence']:.0f}%)",
              f"- {nw['rationale']}", "",
              "## Institutional Levels & Expected Reaction", "",
              "| Strike | Type | Basis | OI | ΔOI | Dist | Expected reaction |",
              "|---|---|---|---|---|---|---|"]
    for l in levels.get("levels", []):
        lines.append(f"| {l['strike']:.0f} | {l['kind']} | {l['basis']} | "
                     f"{l['oi']:,.0f} | {l['oi_change']:+,.0f} | {l['distance_pct']:+.2f}% | "
                     f"{l['reaction']} |")
    lines += ["", f"**Max Pain:** {levels.get('max_pain','n/a')} · "
              f"**PCR:** {levels.get('pcr','n/a')} — {levels.get('pcr_signal','')}", "",
              "## Decode Signals", "",
              "| Signal | Score | Weight | Note |", "|---|---|---|---|"]
    for s in decode_result["signals"]:
        lines.append(f"| {s['name']} | {s['score']:+.2f} | {s['weight']:.2f} | {s['note']} |")
    lines += ["", "---",
              "_Auto-generated by FII-DII-Decode. Educational only — not investment advice._"]
    return "\n".join(lines)
